#!/usr/bin/env node

var spawn = require('child_process').spawn()
process.argv.shift()
process.argv.shift()

var prog = process.argv.shift()
console.dir(prog)
console.dir(process.argv)

spawn(prog, process.argv)



