#!/usr/bin/env node

var spawn = require('child_process').spawn

var args = process.argv

console.dir(args)

args.shift()
args.shift()

var prog = args.shift()
console.dir(prog)
console.dir(args)

var p = spawn(prog, args)


p.stdout.on('data', function (data) {
  console.log('stdout: ' + data);
});


